name: india_air_quality_json

on:
  schedule:
     - cron: '23 * * * *'  # Runs every 45th minute of every hour in IST
  workflow_dispatch:        # Allows manual run as well

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        run: |
          python3 -m pip install --upgrade pip
          pip install "snowflake-snowpark-python[pandas]" requests pytz

      - name: Run ingestion script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_REGION: ${{ secrets.SNOWFLAKE_REGION }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          DATA_GOV_API_KEY: ${{ secrets.DATA_GOV_API_KEY }}
        run: |
          python air-quality-data-ingestion/ingest-api-data.py
